---
- name: Get AWS subnet info
  hosts: localhost
  connection: local
  tasks:
    - name: Task to get route table info
      ec2_vpc_subnet_info:
#        aws_access_key: "{{ aws_access_key }}"
#        aws_secret_key: "{{ aws_secret_key }}"
        aws_region: "{{ aws_region }}"
        filters:
          tag:vpc_name: ansible_tower
      register: ansible_aws_subnet_info

    - name: List AWS route table  info
      debug:
        msg: "{{ ansible_aws_subnet_info.subnets[0].subnet_id  }}"
      when:  ansible_aws_subnet_info.subnets != []

