---
- name: Get AWS VPC net info
  hosts: localhost
  connection: local
  tasks:
    - name: Task to get VPC info
      ec2_vpc_net_info:
#        aws_access_key: "{{ aws_access_key }}"
#        aws_secret_key: "{{ aws_secret_key }}"
        aws_region: "{{ aws_region }}"
        filters:
          "tag:Name": "ansible_tower_vpc"
      register: ansible_aws_vpc_info

    - name: List AWS facts
      debug:
        msg: "{{ ansible_aws_vpc_info.vpcs[0]  }}"
      when:  ansible_aws_vpc_info.vpcs != []

