--- 
- name: Play to create EC2 resources and finally a RHEL 8 instance
  hosts: localhost
  connection: local
  vars:
    aws_region: us-west-1
    aws_vpc_name: ansible_tower
  tasks:
    - name: Task to create the VPC
      ec2_vpc_net:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        name: ansible_tower_vpc
        cidr_block: 10.10.0.0/16
        region: "{{ aws_region }}"
        tenancy: default
        tags:
          vpc_name: "{{ aws_vpc_name }}"
      register: ansible_tower_vpc
      
    - name: debug
      debug:
        msg: "{{ ansible_tower_vpc }}"
    
    - name: Create an Internet Gateway and associate to the VPC
      ec2_vpc_igw:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        vpc_id: "{{ ansible_tower_vpc.vpc.id }}"
        region: "{{ aws_region }}"
        tags:
          vpc_name: "{{ aws_vpc_name }}"
        state: present
      register: ansible_tower_igw

    - name: Create a subnet in the VPC
      ec2_vpc_subnet:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        state: present
        vpc_id: "{{ ansible_tower_vpc.vpc.id }}"
        cidr: 10.10.0.0/20
        tags:
          vpc_name: "{{ aws_vpc_name }}"
        region: "{{ aws_region }}"
      register: ansible_tower_subnet

    - name: Set up public subnet route table
      ec2_vpc_route_table:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        vpc_id: "{{ ansible_tower_vpc.vpc.id }}"
        region: "{{ aws_region }}"
        tags:
          vpc_name: "{{ aws_vpc_name }}"
        subnets: 
          - "{{ ansible_tower_subnet.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ ansible_tower_igw.gateway_id }}"
    - name: Task to create AWS Security Groups
      ec2_group:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        name: ansible_tower_sg
        description: AWS Security Group for Ansible Tower Demonstration
        vpc_id: "{{ ansible_tower_vpc.vpc.id }}"
        region: "{{ aws_region }}"
        tags:
          vpc_name: "{{ aws_vpc_name }}"
        rules:
          - proto: tcp
            ports: 
              - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all connections on port 22
    - name: create key pair using provided key_material 
      ec2_key: 
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ aws_region }}"
        name: ansible-tower-aws-key
        key_material: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDIro3SN80ckrxyHid65mvuDi2zY8zakQ1G32F8vT2OZtpX8nQ7WgJdqvOYI/Eba83oEZGfI97DZFab2tNVi5GPJoc2wNfd6UVpQTi9DdKuldT9JjYTZuHdEfK+AFixyOtkvabmd7EggZlxtfrZ14mxzTttouWAb6JRQAtQxBGw1Kb7NOijSlxQrX8cqKTNU4ODO3/+du3pFawA2E5LTXuebBhWk5k5BCudQFWNCVlABWuAiblFDv9IvhCnf6c71YflEPyoDdGq5hV/OiKm3fa3i1LBycW61+PpnEf1nCoIhVQYo3jIcaRjJNGPC8DaU6/gbq731WfvPdnqwYOzcAN6ItuLA203ev8Pz2AZ2PvzK9H+QXCxJykYNwxN7daZNRp40RKnf8WD2yZbN7rnlk+HYoqzxqq3KU8HzD7lR1WNIuqVjVoYH4NqoeslX8FGKsG2BiQQt5fw/WcFKcbiopUa4ab0rACxidNB38ppMj9sgFGjOFPzHLQcyBo8WajL/7dSDZ0QTO2dRSpJSJ4n3aMmCBhoF/WXPrunNTMhUFoSLleQmy9Vvc2/cOy6+SWvN+bELHKm9AkEfaHSaEtH9CshimjPHf6sStdZoQi4IIO83FLeedzH5XU589Z5aXzoWv8x6BoIpJMCdzqOqojNKzHqOEsQEfOe2NAAHfseS65cvw== My AWS SSH Keys'
      
    - name: Task to provision the RHEL EC2 instance
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ aws_region }}"
        key_name: ansible-tower-aws-key
        instance_type: t2.micro
        image: ami-054965c6cd7c6e462
        wait: yes
        group: ansible_tower_sg
        count: 1
        vpc_subnet_id: "{{ ansible_tower_subnet.subnet.id }}" 
        assign_public_ip: yes

