---
- name: Get AWS facts
  hosts: localhost
  connection: local
  vars:
    aws_region: us-west-1
  tasks:
    - name: Task to create the VPC
      ec2_instance_info:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        aws_region: "{{ aws_region }}"
        filters:
          instance-state-name: [ "running"]
      register: ansible_ec2_info

    - name: List AWS facts
      debug:
        msg: "{{ ansible_ec2_info.instances[0].instance_id }}"
      when:  ansible_ec2_info.instances != []

