---
- name: Get AWS SG  info
  hosts: localhost
  connection: local
  tasks:
    - name: Task to get SG info
      ec2_group_info:
#        aws_access_key: "{{ aws_access_key }}"
#        aws_secret_key: "{{ aws_secret_key }}"
        aws_region: "{{ aws_region }}"
        filters:
          group_name: ansible_tower_sg
      register: ansible_aws_sg_info

    - name: List AWS SG info
      debug:
        msg: "{{ ansible_aws_sg_info  }}"
      when:  ansible_aws_sg_info.security_groups!= []

