---
- name: Get AWS route info
  hosts: localhost
  connection: local
  tasks:
    - name: Task to get route table info
      ec2_vpc_route_table_info:
#        aws_access_key: "{{ aws_access_key }}"
#        aws_secret_key: "{{ aws_secret_key }}"
        aws_region: "{{ aws_region }}"
        filters:
          tag:vpc_name: ansible_tower
      register: ansible_aws_route_info

    - name: List AWS route table  info
      debug:
        msg: "{{ ansible_aws_route_info.route_tables[0].id  }}"
      when:  ansible_aws_route_info.route_tables!= []

