--- 
- name: Play to create EC2 resources and finally a RHEL 8 instance
  hosts: localhost
  connection: local
  vars:
    aws_region: us-west-1
    aws_vpc_name: ansible_tower
  tasks:
    - name: Task to get VPC info
      ec2_vpc_net_info:
#        aws_access_key: "{{ aws_access_key }}"
#        aws_secret_key: "{{ aws_secret_key }}"
        aws_region: "{{ aws_region }}"
        filters:
          "tag:Name": "ansible_tower_vpc"
      register: ansible_tower_vpc

    - name: Task to get route table info
      ec2_vpc_subnet_info:
#        aws_access_key: "{{ aws_access_key }}"
#        aws_secret_key: "{{ aws_secret_key }}"
        aws_region: "{{ aws_region }}"
        filters:
          tag:vpc_name: ansible_tower
      register: ansible_aws_subnet

    - name: Task to get IGW info
      ec2_vpc_igw_info:
#        aws_access_key: "{{ aws_access_key }}"
#        aws_secret_key: "{{ aws_secret_key }}"
        aws_region: "{{ aws_region }}"
        filters:
         #  "tag:Name": "ansible_tower_vpc"
          tag:vpc_name: ansible_tower
      register: ansible_aws_igw

    - name: List AWS IGW info
      debug:
        msg: "{{ ansible_aws_igw.internet_gateways[0].internet_gateway_id  }}"
      when:  ansible_aws_igw.internet_gateways != []


    - name: Set up public subnet route table
      ec2_vpc_route_table:
 #       aws_access_key: "{{ aws_access_key }}"
 #       aws_secret_key: "{{ aws_secret_key }}"
        vpc_id: "{{ ansible_tower_vpc.vpcs[0].id }}"
        region: "{{ aws_region }}"
        tags:
          vpc_name: "{{ aws_vpc_name }}"
        subnets: 
          - "{{ ansible_aws_subnet.subnets[0].subnet_id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ ansible_aws_igw.internet_gateways[0].internet_gateway_id  }}"

