--- 
- name: Play to create EC2 resources and finally a RHEL 8 instance
  hosts: localhost
  connection: local
  vars:
    aws_region: us-west-1
    aws_vpc_name: ansible_tower
  tasks:
    - name: Task to get VPC info
      ec2_vpc_net_info:
#        aws_access_key: "{{ aws_access_key }}"
#        aws_secret_key: "{{ aws_secret_key }}"
        aws_region: "{{ aws_region }}"
        filters:
          "tag:Name": "ansible_tower_vpc"
      register: ansible_tower_vpc

    - name: List AWS facts
      debug:
        msg: "{{ ansible_tower_vpc.vpcs[0]  }}"
      when:  ansible_tower_vpc.vpcs != []

    - name: Create a subnet in the VPC
      ec2_vpc_subnet:
#        aws_access_key: "{{ aws_access_key }}"
#        aws_secret_key: "{{ aws_secret_key }}"
        state: present
        vpc_id: "{{ ansible_tower_vpc.vpcs[0].id }}"
        cidr: 10.10.0.0/20
        tags:
          vpc_name: "{{ aws_vpc_name }}"
        region: "{{ aws_region }}"
      register: ansible_tower_subnet

